theme: jekyll-theme-dinky
title: Ben Harris
description: My personal page
show_downloads: false
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      author: "Ben Harris"
